const VERIFICATION_STATUSES = Object.freeze([
  'NOT_STARTED',
  'PENDING',
  'UNDER_REVIEW',
  'VERIFIED',
  'REJECTED',
  'RESUBMISSION_REQUIRED',
]);

const VERIFICATION_PROVIDERS = Object.freeze(['MANUAL', 'DIGILOCKER', 'CASHFREE']);
const DOCUMENT_CATEGORIES = Object.freeze(['IDENTITY', 'BUSINESS', 'BANK']);
const DOCUMENT_TYPES = Object.freeze([
  'PAN',
  'DRIVING_LICENCE',
  'OTHER_IDENTITY',
  'GSTIN',
  'CIN',
  'BUSINESS_REGISTRATION',
  'BANK_PROOF',
  'CANCELLED_CHEQUE',
]);
const AUTHORIZATION_DOCUMENT_TYPES = Object.freeze([
  'OWNERSHIP_PROOF',
  'LEASE',
  'NOC',
  'AUTHORIZATION_LETTER',
  'OTHER',
]);

module.exports = {
  VERIFICATION_STATUSES,
  VERIFICATION_PROVIDERS,
  DOCUMENT_CATEGORIES,
  DOCUMENT_TYPES,
  AUTHORIZATION_DOCUMENT_TYPES,
};
